### ISSUE TITLE
Test v4 GET presigned URLs

### ISSUE THREAD

**Issue by fczuardi** [marmotitude/object-storage-tests#65]
Today we cover presigned PUT with boto3 (v4) and presigned GET with aws-cli (v2).

It would be nice to have a test that generates a (v4) presigned GET URL and then make the download.

**Comment by folkzb** [comment]
hey @fczuardi, in https://github.com/marmotitude/object-storage-tests/blob/main/src/k6/aws-cli-presigned.js#L47  is used presigned v4, why is descripted with v2, i dont know but, in use is v4.

**Comment by fczuardi** [comment]
hmm, nevermind them we can close this issue as invalid

**Comment by folkzb** [comment]
https://github.com/marmotitude/object-storage-tests/pull/68, open pr for change tags and log of presign

**Comment by folkzb** [comment]
Done
